### ISSUE TITLE
Any hope for an update?

### ISSUE THREAD

**Issue by l8gravely** [ryanfobel/Adafruit-Eagle-Library.kicad#1]
Ryan,
Thanks for this work, any hope for an update from the latest AdaFruit library?  Specifically looking for the Gemma M0 board stuff...

**Comment by colinlove** [comment]
While you're updating, I had to edit line 4166 to replace " with inch to get it to work in KiCad.
Still didn't have what I wanted though (GPS breakout board).

**Comment by KEClaytor** [comment]
Great work, any change for an update?

**Comment by ryanfobel** [comment]
Sorry, the [source library](https://github.com/adafruit/Adafruit-Eagle-Library) from Adafruit hasn't been updated since 2015, so there's not much I can do from my end.
